// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9t9l0ajwDDF_Kex5vifnb4qJlm--7yw8',
    appId: '1:1067334725424:web:08d7566168bb29185062f5',
    messagingSenderId: '1067334725424',
    projectId: 'landing-e1568',
    authDomain: 'landing-e1568.firebaseapp.com',
    storageBucket: 'landing-e1568.firebasestorage.app',
    measurementId: 'G-NYPK5CYE9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp7SRJK53Ttx5PDqa4-WosPhAMEPWyAmg',
    appId: '1:1067334725424:android:a4fb735abbb222c45062f5',
    messagingSenderId: '1067334725424',
    projectId: 'landing-e1568',
    storageBucket: 'landing-e1568.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9t9l0ajwDDF_Kex5vifnb4qJlm--7yw8',
    appId: '1:1067334725424:web:294df62ad98ce41d5062f5',
    messagingSenderId: '1067334725424',
    projectId: 'landing-e1568',
    authDomain: 'landing-e1568.firebaseapp.com',
    storageBucket: 'landing-e1568.firebasestorage.app',
    measurementId: 'G-EQY1Z88LQD',
  );
}
